/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_taihua_SerialPort
#define _Included_com_taihua_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_taihua_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_taihua_pishamachine_SerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint,jint );

/*
 * Class:     com_taihua_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_taihua_pishamachine_SerialPort_close
  (JNIEnv *, jobject);



#ifdef __cplusplus
}
#endif
#endif
